---

- name: Install fluentd-plugins
  gem: name={{ item }} state=latest executable="/usr/sbin/td-agent-gem" user_install=false
  with_items:
    - fluent-plugin-grep
    - fluent-plugin-record-reformer
    - fluent-plugin-elasticsearch
  notify: restart fluentd

- name: deploy td-agent.log conf file
  template: >
    src=td-agent.j2 dest={{ conf_path }}/td-agent.conf owner=root group=root mode=0644
  sudo: True
  notify: restart td-agent


