remote_user: fih
yum_repo_path: /etc/yum.repos.d

kibana_conf_path: /opt/kibana/config
user: kibana
group: kibana

server_port: 9999
server_host: "10.58.70.98"
elasticsearch_url: "http://10.58.70.98:9200"
elasticsearch_host: "10.58.70.98"
elasticsearch_port: "9200"
